version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    command: uvicorn main:socket_app --host 127.0.0.1 --port 8080
    env_file:
      - backend/.env
    restart: always
