"""initial_base_schema

Revision ID: 6bc18fc973db
Revises: 
Create Date: 2026-05-22 22:07:11.114295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc18fc973db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_history', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('courses', 'id_reg',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('student_roadmap', 'semester',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Fall'"))
    op.drop_column('student_roadmap', 'mark')
    op.alter_column('students', 'advisor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'students', 'cs_faculty_info', ['advisor_id'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.alter_column('students', 'advisor_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('student_roadmap', sa.Column('mark', sa.FLOAT(), nullable=True))
    op.alter_column('student_roadmap', 'semester',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Fall'"))
    op.alter_column('courses', 'id_reg',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('chatbot_history', 'source')
    # ### end Alembic commands ###
