"""remove student_id relation from courses

Revision ID: cede5b01bdc6
Revises: 25ae34574405
Create Date: 2026-04-28 20:38:12.419569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cede5b01bdc6'
down_revision: Union[str, Sequence[str], None] = '25ae34574405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('prerequisites', sa.VARCHAR(), nullable=True),
    sa.Column('plan_type', sa.VARCHAR(), nullable=True),
    sa.Column('credit_hours', sa.VARCHAR(), nullable=True),
    sa.Column('year_and_semester', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.university_id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    # ### end Alembic commands ###
